export const VUEXBLAZE_STOP_ON_UNCONTROLLABLE_CHANGE = "stop"
export const VUEXBLAZE_IGNORE_ON_UNCONTROLLABLE_CHANGE = 'ignore'

export default {
  VUEXBLAZE_STOP_ON_UNCONTROLLABLE_CHANGE,
  VUEXBLAZE_IGNORE_ON_UNCONTROLLABLE_CHANGE
}