export const VUEXBLAZE_STOP_ON_UNCONTROLLABLE_CHANGE = 'stop'
export const VUEXBLAZE_IGNORE_ON_UNCONTROLLABLE_CHANGE = 'ignore'
export const VUEXBLAZE_CAMEL_CASE = 'camel'
export const VUEXBLAZE_SNAKE_CASE = 'snake'
export const VUEXBLAZW_CONST_CASE = 'const'

export default {
  STOP_ON_UNCONTROLLABLE_CHANGE: VUEXBLAZE_STOP_ON_UNCONTROLLABLE_CHANGE,
  IGNORE_ON_UNCONTROLLABLE_CHANGE: VUEXBLAZE_IGNORE_ON_UNCONTROLLABLE_CHANGE
}
