export const VUEXBLAZE_STOP_ON_UNCONTROLLABLE_CHANGE = 'stop'
export const VUEXBLAZE_IGNORE_ON_UNCONTROLLABLE_CHANGE = 'ignore'
export const VUEXBLAZE_CAMEL_CASE = 'camelcase'
export const VUEXBLAZE_SNAKE_CASE = 'snakecase'
export const VUEXBLAZW_SCREAMING_SNAKE_CASE = 'screamingsnakecase'

export default {
  STOP_ON_UNCONTROLLABLE_CHANGE: VUEXBLAZE_STOP_ON_UNCONTROLLABLE_CHANGE,
  IGNORE_ON_UNCONTROLLABLE_CHANGE: VUEXBLAZE_IGNORE_ON_UNCONTROLLABLE_CHANGE
}
