export const VUEXBLAZE_COLLECTION_ADD = 'vuexblaze/COLLECTION_ADD'
export const VUEXBLAZE_COLLECTION_REMOVE = 'vuexblaze/COLLECTION_REMOVE'
export const VUEXBLAZE_COLLECTION_MODIFY = 'vuexblaze/COLLECTION_MODIFY'
export const VUEXBLAZE_COLLECTION_CLEAR = 'vuexblaze/COLLECTION_CLEAR'
export const VUEXBLAZE_SET_PATH = 'vuexblaze/SET_PATH'

export default {
  VUEXBLAZE_COLLECTION_ADD,
  VUEXBLAZE_COLLECTION_REMOVE,
  VUEXBLAZE_COLLECTION_MODIFY,
  VUEXBLAZE_COLLECTION_CLEAR,
  VUEXBLAZE_SET_PATH
}