export const VUEXBLAZE_SET_VALUE = 'vuexblaze/SET_VALUE'
export const VUEXBLAZE_COLLECTION_ADD = 'vuexblaze/COLLECTION_ADD'
export const VUEXBLAZE_COLLECTION_REMOVE = 'vuexblaze/COLLECTION_REMOVE'
export const VUEXBLAZE_COLLECTION_SPLICE = 'vuexblaze/COLLECTION_SPLICE'